name: new_scanner_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^5.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

# PHẦN NÀY LÀ QUAN TRỌNG NHẤT
dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0

  flutter_launcher_icons: ^0.14.4


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


# THÊM MỤC CẤU HÌNH ICON VÀO CUỐI CÙNG
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"